### ISSUE TITLE
Messed up characters in  0.1.1b-svn

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#97] opened 2015-07-25 13:11 UTC
```
If reporting a bug, please ensure the bug is present in the latest
developmental source (checkout from SVN). Some major bugs have been fixed
already.

What steps will reproduce the problem?
1. Compile  0.1.1b-svn in Ubuntu 12.04 64 Bit
2. Use USB keyboard
3. Do key strokes and see the log

What is the expected output?
Correct keys being logged

What do you see instead?
Garbage being logged (except for function keys)
Example: "euar1234" is "rift1234"

What version of the product are you using (`logkeys --help`)?
0.1.1b-svn

On what operating system?
Ubuntu 12.04

Please provide any additional information below.
If applicable, also attach contents of /proc/bus/input/devices, the output
of command `dumpkeys -n > dumpkeys.output`, and any
other relevant files.

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=PNP0C0C/button/input0
S: Sysfs=/devices/LNXSYSTM:00/device:00/PNP0C0C:00/input/input0
U: Uniq=
H: Handlers=kbd event0 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=LNXPWRBN/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0003 Vendor=04f3 Product=0103 Version=0110
N: Name="HID 04f3:0103"
P: Phys=usb-0000:00:1d.2-1/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.2/usb4/4-1/4-1:1.0/input/input2
U: Uniq=
H: Handlers=sysrq kbd event2 
B: PROP=0
B: EV=120013
B: KEY=1000000000007 ff800000000007ff febeffdff3cfffff fffffffffffffffe
B: MSC=10
B: LED=7

I: Bus=0003 Vendor=04f3 Product=0103 Version=0110
N: Name="HID 04f3:0103"
P: Phys=usb-0000:00:1d.2-1/input1
S: Sysfs=/devices/pci0000:00/0000:00:1d.2/usb4/4-1/4-1:1.1/input/input3
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=1f
B: KEY=4837fff072ff32d bf54444600000000 1 20c100b17c000 267bfad941dfed 
9e168000004400 10000002
B: REL=40
B: ABS=100000000
B: MSC=10

I: Bus=0003 Vendor=093a Product=2510 Version=0111
N: Name="PIXART USB OPTICAL MOUSE"
P: Phys=usb-0000:00:1d.3-1/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.3/usb5/5-1/5-1:1.0/input/input4
U: Uniq=
H: Handlers=mouse0 event4 
B: PROP=0
B: EV=17
B: KEY=70000 0 0 0 0
B: REL=103
B: MSC=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel Line"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input5
U: Uniq=
H: Handlers=event5 
B: PROP=0
B: EV=21
B: SW=2000

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel Front Mic"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input6
U: Uniq=
H: Handlers=event6 
B: PROP=0
B: EV=21
B: SW=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel Rear Mic"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input7
U: Uniq=
H: Handlers=event7 
B: PROP=0
B: EV=21
B: SW=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel Front Headphone"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input8
U: Uniq=
H: Handlers=event8 
B: PROP=0
B: EV=21
B: SW=4

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel Line-Out"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input9
U: Uniq=
H: Handlers=event9 
B: PROP=0
B: EV=21
B: SW=40
```

Original issue reported on code.google.com by `vladimir...@gmail.com` on 30 Oct 2012 at 9:34

Attachments:
* [dumpkeys.output](https://storage.googleapis.com/google-code-attachments/logkeys/issue-97/comment-0/dumpkeys.output)

**Comment by kernc** [comment] 2016-02-07 11:34
Duplicate of https://github.com/kernc/logkeys/issues/28

**Closed by kernc** 2016-02-07 11:34 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
