### ISSUE TITLE
Junk characters on Fedora 20 (x86_64)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#118] opened 2015-07-25 13:11 UTC
```
I am getting junk characters in the loggy.log file irrespective of whichever 
layout I choose on Fedora 20 (x86_64) running Mate window manager.

What steps will reproduce the problem?

  1. Install logkeys from git (SHA1 6276dd827279dd8c9e959d5c57e6c4b9b85ef08f)
  2. Start logkeys service
  3. Type text in keyboard

I have both QWERTY and Dvorak layouts on my system, and keying in with the 
chosen layout enters the correct characters on the screen. The loggy.log has 
incorrect data.

What is the expected output (QWERTY layout)?

  asdfghjkl

What do you see instead?

  =ȁ܂aoeuid

If I switch to Dvorak layout on the GUI, and run the test, I observe:

What is the expected output (Dvorak layout)?

  aoeuidhtn

What do you see instead?

   =ȁ܂aoeuid

What version of the product are you using (`logkeys --help`)?

  logkeys from SHA1 6276dd827279dd8c9e959d5c57e6c4b9b85ef08f.

On what operating system?

  Fedora 20 (x86_64)

Please provide any additional information below.
If applicable, also attach contents of /proc/bus/input/devices, the output
of command `dumpkeys -n > dumpkeys.output`, and any
other relevant files.

# cat /etc/systemd/system/lk.service

[Unit]
Description=Log Key

[Service]
Type=forking
ExecStart=/usr/local/bin/logkeys -s -u -d /dev/input/event3 -o 
/home/shaks/installs/lk/loggy.log

[Install]
WantedBy=multi-user.target

$ env | grep LANG
LANG=en_US.UTF-8

$ locale -a | grep en_US
en_US
en_US.iso88591
en_US.iso885915
en_US.utf8
```

Original issue reported on code.google.com by `shakthim...@gmail.com` on 19 Jun 2014 at 12:01

Attachments:
* [dumpkeys.output](https://storage.googleapis.com/google-code-attachments/logkeys/issue-118/comment-0/dumpkeys.output)
* [proc-bus-input-devices.txt](https://storage.googleapis.com/google-code-attachments/logkeys/issue-118/comment-0/proc-bus-input-devices.txt)

**Comment by kernc** [comment] 2016-02-07 11:34
Duplicate of https://github.com/kernc/logkeys/issues/28

**Closed by kernc** 2016-02-07 11:34 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
