### ISSUE TITLE
Empty log file with the correct event ID

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#112] opened 2015-07-25 13:11 UTC
```
If reporting a bug, please ensure the bug is present in the latest
developmental source (checkout from SVN). Some major bugs have been fixed
already.

What steps will reproduce the problem?
1.Hardware: Wireless USB Keyboard
2.Linux 3.8.0-25-generic #37-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux; apt-get 
install logkeys
3.Action: touch test.log; sudo logkeys --start -d event2 -o test.log

What is the expected output?
The pressed keys from the USB keyboard

What do you see instead?
Empty log file, no errors

What version of the product are you using (`logkeys --help`)?
logkeys version: 0.1.1a

On what operating system?
Linux 3.8.0-25-generic #37-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

Please provide any additional information below.
Even the compiled version provides the same result.

If applicable, also attach contents of /proc/bus/input/devices, the output
of command `dumpkeys -n > dumpkeys.output`, and any
other relevant files.


```

Original issue reported on code.google.com by `neagarudan` on 28 Jun 2013 at 7:11

Attachments:
* [dumpkeys](https://storage.googleapis.com/google-code-attachments/logkeys/issue-112/comment-0/dumpkeys)
* [keymap](https://storage.googleapis.com/google-code-attachments/logkeys/issue-112/comment-0/keymap)

**Comment by kernc** [comment] 2016-02-15 20:31
Probably a duplicate of https://github.com/kernc/logkeys/issues/108

**Closed** 2016-02-16 15:50 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
