### ISSUE TITLE
records gibberish

### ISSUE THREAD

**Issue by tkalfaoglu** [kernc/logkeys#175] opened 2017-11-08 16:22 UTC
while it was working fine for some time, now the application records gibberish -- nothing like what is typed. What is recorded is illegible. This is on a national (non-US/UK) keyboard.

**Comment by kernc** [comment] 2017-11-08 16:38
Was the keyboard perhaps changed? Reviewing the [commit log](https://github.com/kernc/logkeys/commits/master), one can see not much has changed recently that would seem related. The [keymapping code](https://github.com/kernc/logkeys/blob/master/src/keytables.cc) had always been flakey, defunct for either pc104 or pc105 keyboards; can't remember.

**Comment by tkalfaoglu** [comment] 2017-11-08 17:24
the same computer with the same keyboard. it used to work fine some months back.

**Comment by kernc** [comment] 2017-11-08 17:27
Were you perhaps using one of the [pre-provided keymaps](https://github.com/kernc/logkeys/tree/master/keymaps) before?

**Comment by kernc** [comment] 2018-06-19 22:01
Probably a duplicate of https://github.com/kernc/logkeys/issues/162.

**Closed by kernc** 2018-06-19 22:01 UTC
