### ISSUE TITLE
swiss german keymap

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#102] opened 2015-07-25 13:11 UTC
```
I manually made a swiss german keymap. (on Ubuntu 12.10 with logkeys v0.1.1a)
```

Original issue reported on code.google.com by `jan.herm...@gmail.com` on 26 Dec 2012 at 2:25

Attachments:
* [de-ch.map](https://storage.googleapis.com/google-code-attachments/logkeys/issue-102/comment-0/de-ch.map)

**Comment by jzohrab** [comment] 2016-02-11 15:43
Duplicate of https://github.com/kernc/logkeys/issues/121, closing.

**Closed by jzohrab** 2016-02-11 15:43 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
