### ISSUE TITLE
logkeys outputs wrong characters

### ISSUE THREAD

**Issue by anasbalkhadir** [kernc/logkeys#181] opened 2018-04-16 17:14 UTC
The programme runs buts some characters are false,  for example letter b corresponds to letter v and they are many other cases that I list.  Then  I realise programme that  "decrypts" a String from the log-key  [file](https://github.com/anasbalkhadir/logkeys)

**Comment by kernc** [comment] 2018-04-16 17:29
Have you perhaps tried to use a different [keymap](https://github.com/kernc/logkeys/tree/master/keymaps), specified with `-m` program option? Or create and submit a new one for your language/layout?

**Comment by kernc** [comment] 2018-06-19 22:01
Probably a duplicate of https://github.com/kernc/logkeys/issues/162.

**Closed by kernc** 2018-06-19 22:01 UTC
