### ISSUE TITLE
Does nothing on raspberry pi

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#103] opened 2015-07-25 13:11 UTC
```
Tested on svn and lastest alfa release.

What steps will reproduce the problem?
1. Compile on raspberry pi
2. Run
3. Get the help message

Running this on arm returns the usage() message.
I'm trying to debug this out, I'll tell you later (have to go).

Basically, it seems to be executing the default case in the args switch 
everytime.

```

Original issue reported on code.google.com by `m...@davidfrancos.net` on 5 Jan 2013 at 6:51

**Comment by MITREhacks** [comment] 2015-10-20 21:35
Issue is `char` being treated as `unsigned char` instead of `signed char`. Can fix by compiling with `-fsigned-char`

Annoying, but C standard doesn't define what "char" has to be. And different distro's have different thoughts on this...

**Comment by eugenekolo** [comment] 2015-10-20 21:37
Issue is char being treated as unsigned char instead of signed char. Can fix by compiling with -fsigned-char

Annoying, but C standard doesn't define what "char" has to be. And different distro's have different thoughts on this...

**Comment by robster0326** [comment] 2016-02-15 17:20
Hey, 

the same here as well... always the usage screen pops up :(

**Comment by eugenekolo** [comment] 2016-02-15 17:45
@robster0326 

Few solutions:

1) Change line 60 of src/args.cc from `char c` to `unsigned char c`.  
This is what I did, and it'll work. But it doesn't fit the root cause of the issue.

2) Change every `char` to be EXPLICITLY `unsigned` or `signed`.  
Have not tested this. It should work, but it's hard to figure out what has to be what.

3) Figure out the Makefile, and place a '-fsigned-char' flag somewhere in it.  
Same as (2). Should work, untested, might break stuff.

**Comment by jzohrab** [comment] 2016-02-15 18:22
@robster0326 and @eugenekolo - I don't have a pi and so can't test it, unfortunately.  If you can make a branch with your change, I can test it on an ubuntu 1404 VM.  I'm not sure how to test for multiple platforms, any ideas?

**Comment by robster0326** [comment] 2016-02-16 06:11
Thx, but nothing has changed :(

**Comment by radavis** [comment] 2016-02-20 19:42
So, I'm working from a Beaglebone White, which, as far as I know, has a similar OS as the Raspberry Pi.

```
root@beaglebone:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.3 (jessie)
Release:	8.3
Codename:	jessie

root@beaglebone:~# uname -mrs
Linux 4.1.15-ti-rt-r43 armv7l
```

I was having a similar issue as others, where, after running the instructions in `INSTALL`, ended up with an application that would only output the "help" dialog. I was at least able to get a step further than this by doing the following:

```
$ apt-get update
$ apt-get install build-essential kbd
$ git clone https://github.com/kernc/logkeys.git
```

Change line 1 of `src/Makefile.am` to:

```
AM_CXXFLAGS = -Wall -O3 -DSYS_CONF_DIR=\"$(sysconfdir)\" -fsigned-char
```

Follow instructions in `INSTALL` to build from source.

I have a USB keyboard plugged into the single USB port of the Beaglebone. In a ssh connection, I can do the following:

```
root@beaglebone:~# logkeys -s -u -d event1 -o logkeys.log
root@beaglebone:~# tail -f logkeys.log

Logging started ...

2016-02-20 19:40:31+0000 > fu qfȁr ȁew tiy yo rii<LShft>m
2016-02-20 19:40:53+0000 > ^C
```

The output isn't quite what it should be. But, I was able to get a step further than seeing the 'help' dialog!

**Comment by radavis** [comment] 2016-02-20 20:38
Got it! Ignore my previous comment on changing `src/Makefile.am`. Here is what worked for me...

First, get to a clean state.
```
$ cd build
$ make uninstall
$ cd ..
$ git checkout -- .
```

Change line 60 of `src/args.cc`, as @eugenekolo instructed. 

```
  signed char c; // src/args.cc:60
```

Follow instructions in `INSTALL` to build from source.

After this, I was still getting some strange output from my keyboard, until I used one of the keymaps provided:

```
$ logkeys -s -m logkeys/keymaps/en_US_ubuntu_1204.map -o test.log -d event1
```

I hope this helps, @robster0326. I see if I can give this a shot on a Raspberry Pi sometime soon.

**Comment by robster0326** [comment] 2016-02-23 20:57
Hey,

thx for the suggestions. Will try during the weekend.

Br,

rob

**Comment by jzohrab** [comment] 2016-02-23 21:35
I'm not able to test this out, or confidently change the code to resolve your troubles.  If you can work it out and submit a PR that would fix `master` for all, that would be great and I'd be interested to see it.  Thanks!

**Comment by JElchison** [comment] 2017-12-08 18:42
I'm running a Raspberry Pi, and ran into this issue.  For me, all that was necessary to workaround it was to compile from source, on the Raspberry Pi itself.  I had success with 5c368327a2cd818efaed4794633c260b90b87abf.

**Comment by eugenekolo** [comment] 2017-12-09 01:40
This was fixed in https://github.com/kernc/logkeys/commit/355d1f832768d4629a6b4b224ca13dbfbc5fd340 it seems.

You can close now.

**Comment by kernc** [comment] 2017-12-09 04:07
Thanks.

**Closed by kernc** 2017-12-09 04:07 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect

**Comment by JElchison** [comment] 2017-12-09 16:08
Agree, that seems plausible.  The version of logkeys in the Raspbian repo is `0.1.1a+git5ef6b0dcb9e3-2`, which is really old (and, more importantly, before 355d1f8).

Thanks for the great tool!
