### ISSUE TITLE
empty  log file UBUNTU 12.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#104] opened 2015-07-25 13:11 UTC
```
If reporting a bug, please ensure the bug is present in the latest
developmental source (checkout from SVN). Some major bugs have been fixed
already.

Logkeys works perfectly in version 12.04, updated my Ubuntu to version 12.10 
and LogKeys stopped working


What steps will reproduce the problem?

aW : PHILCO NETBOOK PHN 11A-P123WS

erroR : empty log file


What is the expected output?

aW : log of keyboard


What do you see instead?

aw : nothing


What version of the product are you using (`logkeys --help`)?

aw :
gabriel@gabriel:~$ dpkg -l | grep logkeys
ii  logkeys                                   0.1.1a-3                          
        i386         keylogger for GNU/Linux systems


On what operating system?

gabriel@gabriel:~$ uname -a
Linux gabriel 3.5.0-21-generic #32-Ubuntu SMP Tue Dec 11 18:52:46 UTC 2012 i686 
i686 i686 GNU/Linux


Please provide any additional information below.
If applicable, also attach contents of /proc/bus/input/devices, the output
of command `dumpkeys -n > dumpkeys.output`, and any
other relevant files.

gabriel@gabriel:~$ ps -aux | grep logkeys
root       883  0.0  0.0   6480   448 ?        Ss   10:32   0:00 
/usr/bin/logkeys -s -u -d /dev/input/event4 -o /var/log/logkeys


gabriel@gabriel:~$ cat /proc/bus/input/devices
I: Bus=0019 Vendor=0000 Product=0005 Version=0000
N: Name="Lid Switch"
P: Phys=PNP0C0D/button/input0
S: 
Sysfs=/devices/LNXSYSTM:00/device:00/PNP0A08:00/device:02/PNP0C0D:00/input/input
0
U: Uniq=
H: Handlers=event0 
B: PROP=0
B: EV=21
B: SW=1

I: Bus=0019 Vendor=0000 Product=0003 Version=0000
N: Name="Sleep Button"
P: Phys=PNP0C0E/button/input0
S: Sysfs=/devices/LNXSYSTM:00/device:00/PNP0C0E:00/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=4000 0 0 0 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=PNP0C0C/button/input0
S: Sysfs=/devices/LNXSYSTM:00/device:00/PNP0C0C:00/input/input2
U: Uniq=
H: Handlers=kbd event2 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=LNXPWRBN/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input3
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0011 Vendor=0001 Product=0001 Version=ab41
N: Name="AT Translated Set 2 keyboard"
P: Phys=isa0060/serio0/input0
S: Sysfs=/devices/platform/i8042/serio0/input/input4
U: Uniq=
H: Handlers=sysrq kbd event4 
B: PROP=0
B: EV=120013
B: KEY=4 2000000 3803078 f800d001 feffffdf ffefffff ffffffff fffffffe
B: MSC=10
B: LED=7

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/device:00/PNP0A08:00/LNXVIDEO:00/input/input5
U: Uniq=
H: Handlers=kbd event5 
B: PROP=0
B: EV=3
B: KEY=3e000b 0 0 0 0 0 0 0

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel Mic"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input6
U: Uniq=
H: Handlers=event6 
B: PROP=0
B: EV=21
B: SW=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel Front Headphone"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input7
U: Uniq=
H: Handlers=event7 
B: PROP=0
B: EV=21
B: SW=4

I: Bus=0011 Vendor=0002 Product=0007 Version=01b1
N: Name="SynPS/2 Synaptics TouchPad"
P: Phys=isa0060/serio2/input0
S: Sysfs=/devices/platform/i8042/serio2/input/input8
U: Uniq=
H: Handlers=mouse0 event8 
B: PROP=9
B: EV=b
B: KEY=6420 0 30000 0 0 0 0 0 0 0 0
B: ABS=2608000 11000003

```

Original issue reported on code.google.com by `gabriel....@gmail.com` on 7 Jan 2013 at 12:50

**Comment by kernc** [comment] 2016-02-15 20:30
Probably a duplicate of https://github.com/kernc/logkeys/issues/108

**Closed by kernc** 2016-02-15 20:30 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
