### ISSUE TITLE
Postponed letters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kernc/logkeys#127] opened 2015-07-25 13:11 UTC
```
I have problem with the characters. If I press an "g" I get an "l" and if I 
press a "z" I get a "p". So all letters are postponed about 4 letters to the 
right..
The numbers are recorded the right way!!

Does anyone know, why this is happening?

Thanks
```

Original issue reported on code.google.com by `ms123456...@gmail.com` on 31 Jan 2015 at 1:50

**Comment by kernc** [comment] 2016-02-07 11:34
Duplicate of https://github.com/kernc/logkeys/issues/28

**Closed by kernc** 2016-02-07 11:34 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
