### ISSUE TITLE
logkeys serbian us keyboard problem to determine

### ISSUE THREAD

**Issue by exer92** [kernc/logkeys#135] opened 2016-01-10 17:53 UTC
I have a problem with logkeys, 
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sr_RS
LC_TIME=sr_RS
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sr_RS
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sr_RS
LC_NAME=sr_RS
LC_ADDRESS=sr_RS
LC_TELEPHONE=sr_RS
LC_MEASUREMENT=sr_RS
LC_IDENTIFICATION=sr_RS
LC_ALL=
 
when i type asdfghjkl in log shows []ȁ܂asdfg or something like that.
this is a whole log looks like 
2016-01-10 18:48:18+0100 > guafqr] ]qwzy[x t] fqrzu[wȁ iwuzgqc eu ȁqeqwcyxq<LShft>Y s[#q [ iwuzgqc 	yes fqr<BckSp><BckSp><BckSp>guafqr]v 
2016-01-10 18:50:44+0100 >  
2016-01-10 18:50:52+0100 > 	sqx y eriq ]ucqesyxa yx gua ]su	] <BckSp><#+17><BckSp><BckSp><BckSp><BckSp><BckSp><BckSp><BckSp>[]ȁ܂asdfg yx gua ]su	 <BckSp>	 <BckSp><BckSp>] []ȁ܂asdfg<BckSp><BckSp><BckSp><BckSp><BckSp><BckSp><BckSp><BckSp><BckSp> uw]<BckSp> ]ucqesyxa gyfq es[eb
2016-01-10 18:52:29+0100 > esy] y] [ 	sugq guȁ<BckSp>a guf] <BckSp><BckSp><BckSp>uf] gufq<BckSp><BckSp><BckSp>yfq 
2016-01-10 18:52:45+0100 > 

please help here or on exer92@yahoo.com

**Comment by kernc** [comment] 2016-02-07 11:35
Duplicate of https://github.com/kernc/logkeys/issues/28

**Closed by kernc** 2016-02-07 11:35 UTC
